### ISSUE TITLE
Using password problem

### ISSUE THREAD

**Issue by Ken15** [ChicagoSchooler/IdealReserveClient#1]
It is because of my ignorance with this wallet or not. So when I try to fill in the password by using a combination of upper and lower case characters, numbers and symbols also could not be, even though it was made a long password.
Finally I tried to copy and paste a combination of characters scrypt with letters, numbers and symbols which turned out to be almost the same.

If this was a mistake from me, please just ignore my comments.

Thank you
JOsS/csLJGE6swRt+hDeAKK0EDdb8fIGWsBMeMun3zM

**Comment by JimBobCoder** [comment]
Hi Ken15!

Thank you for reporting this issue.  With a fake username & password combination, could you walk me step by step through the problem you're having?

The username & password are hashed using scrypt.  Sometimes, similar inputs will produce similar outputs, but this is coincidence, especially if you're using a very strong combination.

**NOTE:**  The encryption library just started acting up after this most recent Chrome upgrade.  The Scrypt hashing may have the same problem.  I am looking into these problems immediately.

**Comment by ChicagoSchooler** [comment]
Hi Ken15!

Numbers & symbols should be allowed.  In fact, any symbol should be allowed.

There will be times where a password combination's will account number will resemble another's, but the chances of two having the same are astronomically low so long as the password strength checker is doing its job.

Please let me know if you have any more questions or if I did not sufficiently address your concern.

Best luck trader!

**Comment by ChicagoSchooler** [comment]
Closing for now.

Please reopen it if you still think there's a problem.

Thanks Ken15!

**Comment by Ken15** [comment]
Thank you for reply before,

Today I checked my wallet and I check the balance with the total number of coins that I receive is different, for more details may be seen in the following screenshot.

![theidealreserve280315](https://cloud.githubusercontent.com/assets/11590255/6881560/b7e78a38-d596-11e4-8953-0a3360981726.png)

Is this normal? If yes maybe could give me an explanation.

Thank you

**Comment by ChicagoSchooler** [comment]
Ah, yes Ken15, that's the Argus-Nemesis.  There have been trades below the real value of MØ, so the Argus-Nemesis has been cutting supply each time.

It happens to all of us in equal proportions.  There's more on it at CCT: https://cryptocointalk.com/topic/34737-the-argus-nemesis-the-first-public-auction-trade/

Best luck trader!
